version: "3.9"

services:
   school-api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      container_name: School-API-Home
      command: python3 manage.py runserver 0.0.0.0:8000
      # volumes here mounts the code to the container and updates
      # the container when a change to the source code is made.
      # without this you would have to rebuild the image each time
      #changes are made to source code
      volumes:
         - .:/app
      # ports:
      #    - "8000:8000"
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - school-api-home

   postgres-db:
      image: kartoza/postgis:12.0
      ports:
         - 5432:5432
      volumes:
         # for persistent storage
         - postgres_data_home:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DB=${POSTGRES_DB}
      restart: "on-failure"
      networks:
         - school-api-home

   client:
      build:
         context: ./client
         dockerfile: Dockerfile.dev
      container_name: school_frontend_home
      volumes:
         - ./app/node_modules
         - ./client:/app
      depends_on:
         - school-api
      networks:
         - school-api-home

   nginx:
      restart: always
      depends_on:
         - school-api
      build:
         context: ./nginx
         dockerfile: Dockerfile.dev
      ports:
         - 8080:80
      networks:
         - school-api-home

networks:
   school-api-home:
      driver: bridge

volumes:
   postgres_data_home:
